### ISSUE TITLE
Make addfunds a payable function

### ISSUE THREAD

**Issue by eltontay** [anirudhgajula/Betting#5]
This function still needs to be payable.
One more improvement is to remove the value input parameter and have it even more dynamic by taking in msg.value as the bet amount

![Screenshot 2022-12-02 at 8 01 39 AM](https://user-images.githubusercontent.com/57287843/205184550-c03acadf-7642-424b-b69a-f2cc10af750e.png)

**Comment by eltontay** [comment]
One more thing, for future references, issues are only closed after reviews. So keep threads live until issue is resolved!
Good coding practices :)

**Comment by eltontay** [comment]
Furthermore, the previous issue i raised was not solved regarding require functions. Require and modifier functions work similarly and should only be used as checks, not actions that produce change such as transfer of tokens

**Comment by eltontay** [comment]
1. create new branch
2. Work on changes
3. submit pull request
4. Resolve with comments such as
Resolves #1 

https://rewind.com/blog/best-practices-for-using-github-issues/

**Comment by anirudhgajula** [comment]
Hi Elton, I've been trying to resolve this issue, but when testing after setting it to payable, the ERC token balances are not changing. Instead, the function is causing the ether to change. I went to see if other people had the same issues, and according to the links below, the commenters mentioned that payable has to do with ether and that to transfer tokens, transfer/transferFrom methods need to be used. Not sure how to proceed unfortunately

https://stackoverflow.com/questions/53018406/how-to-use-a-payable-function-with-a-erc20-token-with-web3-v1
https://ethereum.stackexchange.com/questions/91580/how-to-send-erc20-token-to-smart-contract-in-constructor

**Comment by eltontay** [comment]
Yes, actually. Leave the parameter for the value in because it is an erc20 token.
However, you can set it to payable and it woks fine.

![Screenshot 2022-12-05 at 5 56 35 PM](https://user-images.githubusercontent.com/57287843/205608033-835a98a1-5739-43bb-870e-7572e1be7a11.png)
